### ISSUE TITLE
v6.0.0-alpha.2: Not able to install Mainsail or Fluidd

### ISSUE THREAD

**Issue by alexthelion335** [dw-0/kiauh#522]
### Linux Distribution

Raspbian bullseye armhf

### What happened

I am unable to install either Mainsail or Fluidd using this script. For context, I am working on upgrading my Ender 3 Pro firmware from Marlin to Klipper. This Raspberry Pi had Octoprint on it before the install, and I was hoping to still be able to use it during the process. After installing Klipper and Moonraker on the Pi, I lost access to Octoprint.

I get the following error message when attempting to install either web interface:

```
[ERROR] An unexpected error occured:
invalid literal for int() with base 10: '127.0.0.128126'
Traceback (most recent call last):
  File "/home/pi/kiauh/kiauh/core/menus/base_menu.py", line 188, in run
    selected_option.method(
  File "/home/pi/kiauh/kiauh/core/menus/install_menu.py", line 88, in install_mainsail
    client_setup.install_client(MainsailData())
  File "/home/pi/kiauh/kiauh/components/webui_client/client_setup.py", line 97, in install_client
    ports_in_use: List[int] = read_ports_from_nginx_configs()
  File "/home/pi/kiauh/kiauh/components/webui_client/client_utils.py", line 331, in read_ports_from_nginx_configs
    ports_to_ints_list = [int(port) for port in port_list]
  File "/home/pi/kiauh/kiauh/components/webui_client/client_utils.py", line 331, in <listcomp>
    ports_to_ints_list = [int(port) for port in port_list]
ValueError: invalid literal for int() with base 10: '127.0.0.128126'
```

### What did you expect to happen

I expected to be able to proceed through the install process with no hiccups and continue to be able to access my Octoprint instance.

### How to reproduce

1. Clone kiuah repo
2. Open script
3. Install Klipper and Moonraker
4. Attempt to install Mainsail

**Comment by alexthelion335** [comment]
I was able to install Mainsail after removing my enabled sites in nginx. I'm still not able to access Octoprint, but hopefully after I get my printer firmware installed, I won't have to.
