### ISSUE TITLE
Klipper git gets disconneced, update fails with 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by arhi** [dw-0/kiauh#611]
### Linux Distribution

v25.2 rolling for mkspi running Armbian Linux 6.12.4-edge-rockchip64

### What happened

Installed klipper, moonraker, mainsail, mainsail-config and klipperscreen

after few weeks klipper show in update manager that it is broken, git status gives:
```

mks@mkspi:~/klipper$ git status
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean
mks@mkspi:~/klipper$ 
```

tried to upgrade, it failed... removed, installed everything from scratch, all new versions
few weeks passed
same thing with klipper

trying to upgrade from kiauh:
```
###### Perform action: 1

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                      [ WARNING ]                      ┃
┠───────────────────────────────────────────────────────┨
┃ Do NOT continue if there are ongoing prints running!  ┃
┃ All Klipper instances will be restarted during the    ┃
┃ update process and ongoing prints WILL FAIL.          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
###### Update Klipper now? (Y/n): 

###### Stop klipper.service ...
[OK] OK!

###### Updating repository 'https://github.com/Klipper3d/klipper' ...
remote: Enumerating objects: 34093, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (54/54), done.
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
[ERROR] An unexpected error occured:
'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/mks/kiauh/kiauh/utils/git_utils.py", line 287, in git_cmd_pull
    run(command, cwd=target_dir, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'pull']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mks/kiauh/kiauh/core/menus/base_menu.py", line 229, in run
    selected_option.method(
  File "/home/mks/kiauh/kiauh/core/menus/update_menu.py", line 196, in update_klipper
    self._run_update_routine("klipper", update_klipper)
  File "/home/mks/kiauh/kiauh/core/menus/update_menu.py", line 305, in _run_update_routine
    update_fn(*args)
  File "/home/mks/kiauh/kiauh/components/klipper/klipper_setup.py", line 206, in update_klipper
    git_pull_wrapper(repo=settings.klipper.repo_url, target_dir=KLIPPER_DIR)
  File "/home/mks/kiauh/kiauh/utils/git_utils.py", line 67, in git_pull_wrapper
    git_cmd_pull(target_dir)
  File "/home/mks/kiauh/kiauh/utils/git_utils.py", line 289, in git_cmd_pull
    log = f"Error on git pull: {e.stderr.decode()}"
                                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'

```

I assume the reason is same as what git is complaining about

![Screenshot 2024-12-26 at 17 51 21](https://github.com/user-attachments/assets/17cf03da-d540-4451-a15d-adea3cffc676)

### What did you expect to happen

I expected klipper to upgrade :D 

### How to reproduce

install klipper, wait few weeks, happened to me twice

no clue how it "detached" from origin

### Additional information

![Screenshot 2024-12-26 at 17 53 39](https://github.com/user-attachments/assets/d8f5f189-f27e-465b-b707-a6db73ea253d)

**Comment by dw-0** [comment]
![image](https://github.com/user-attachments/assets/b6641dde-c470-4aac-b924-8505e56c79ca)

This does not seem to be an issue with KIAUH - closing.
